<?php

namespace App\Exports;

use App\Models\Operaciones\Formatodp;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\Exportable;
class FormatodpExport implements FromQuery,WithHeadings
{

    use Exportable;
    

    
    /**
    * @return \Illuminate\Support\Collection
    */
    public function headings(): array
    {
        return [
                    'TIPDOC',	'IDENTIFICACION',	'NOMBREUNO',	'NOMBREDOS',	'APELLIDOPATERNO',	'APELLIDOMATERNO',	'CARGAS',	'LUGARNACI',	'FECNACIMIENTO',	'NACIONALIDAD',	'NIVELINSTRUC',	'DIRECDOMICILIO',	'REFERENCIADOMICILIO',	'LOCALIDADDOMICILIO',	'CIUDADDOMICILIO',	'COMISIONES',	'CUPOSOLICITADO',	'PROFESION',	'CONYUGUE',	'TIPODOCCONYUGUE',	'IDENTIFICACIONCONYU',	'TLFDOMIC1',	'TLFDOMIC2',	'CELULAR1',	'CELULAR2',	'SEXO',	'ESTADOCIVIL',	'EMAIL',	'EMAIL2',	'TIPOVIVIENDA',	'VALORRENTA',	'TIEMRESIDE',	'TRABAJO',	'DIRECTRABAJO',	'REFERENCIATRABAJO',	'LOCALIDADTRABAJO',	'CARGO',	'SUELDO',	'TIEMTRABAJO',	'CIUDADTRABAJO',	'TLFTRABA1',	'TLFTRABA2',	'EXTTRABA1',	'EXTTRABA2',	'OTROSINGRESOS',	'ORIGENOTROS',	'VALOROTROS',	'TRABAANTERIOR',	'CARGOANTERIOR',	'TLFTRABANTE',	'SUELDOANTERIOR',	'TRABACONYUGUE',	'DIRETRABACONYUGUE',	'CARGOCONYUGUE',	'TLFCONYUGUE',	'SUELDOCONYUGUE',	'REFECOMER1',	'REFECOMER2',	'TLFREFECOMER1',	'TLFREFECOMER2',	'PARIENTEUNO',	'PARENTESCOUNO',	'DIRECPARIUNO',	'TLFPARIUNO',	'PARIENTEDOS',	'PARENTESCODOS',	'DIRECPARIDOS',	'TLFPARIDOS',	'NOMBREPLASTICO',	'TIENDAENTREGA',	'CASILLA',	'CIUDADCASILLA',	'LOCALIDADCASILLA',	'ESTCTADOMICILIO',	'ESTCTATRABAJO',	'ESTCTACASILLA',	'MSGCOBRANZA',	'MSGSALDOS',	'MSGPROPAG','verificar',
                ];
    }




    public function query()
    {
        
        return Formatodp::query()->select(
            'TIPDOC',	'IDENTIFICACION',	'NOMBREUNO',	'NOMBREDOS',	'APELLIDOPATERNO',	'APELLIDOMATERNO',	'CARGAS',	'LUGARNACI',	'FECNACIMIENTO',	'NACIONALIDAD',	'NIVELINSTRUC',	'DIRECDOMICILIO',	'REFERENCIADOMICILIO',	'LOCALIDADDOMICILIO',	'CIUDADDOMICILIO',	'COMISIONES',	'CUPOSOLICITADO',	'PROFESION',	'CONYUGUE',	'TIPODOCCONYUGUE',	'IDENTIFICACIONCONYU',	'TLFDOMIC1',	'TLFDOMIC2',	'CELULAR1',	'CELULAR2',	'SEXO',	'ESTADOCIVIL',	'EMAIL',	'EMAIL2',	'TIPOVIVIENDA',	'VALORRENTA',	'TIEMRESIDE',	'TRABAJO',	'DIRECTRABAJO',	'REFERENCIATRABAJO',	'LOCALIDADTRABAJO',	'CARGO',	'SUELDO',	'TIEMTRABAJO',	'CIUDADTRABAJO',	'TLFTRABA1',	'TLFTRABA2',	'EXTTRABA1',	'EXTTRABA2',	'OTROSINGRESOS',	'ORIGENOTROS',	'VALOROTROS',	'TRABAANTERIOR',	'CARGOANTERIOR',	'TLFTRABANTE',	'SUELDOANTERIOR',	'TRABACONYUGUE',	'DIRETRABACONYUGUE',	'CARGOCONYUGUE',	'TLFCONYUGUE',	'SUELDOCONYUGUE',	'REFECOMER1',	'REFECOMER2',	'TLFREFECOMER1',	'TLFREFECOMER2',	'PARIENTEUNO',	'PARENTESCOUNO',	'DIRECPARIUNO',	'TLFPARIUNO',	'PARIENTEDOS',	'PARENTESCODOS',	'DIRECPARIDOS',	'TLFPARIDOS',	'NOMBREPLASTICO',	'TIENDAENTREGA',	'CASILLA',	'CIUDADCASILLA',	'LOCALIDADCASILLA',	'ESTCTADOMICILIO',	'ESTCTATRABAJO',	'ESTCTACASILLA',	'MSGCOBRANZA',	'MSGSALDOS',	'MSGPROPAG','verificar'
           )
            ->from('DAMPLUSFormatodp');

       
    }
}
