<?php

namespace App\Models\Operaciones;

use Illuminate\Database\Eloquent\Model;

class Formatodp extends Model
{
    public $timestamps = false;
    protected $connection = 'sqlsrv4';
    protected $table ='DAMPLUSFormatodp';
    protected $fillable = ['TIPDOC',	'IDENTIFICACION',	'NOMBREUNO',	'NOMBREDOS',	'APELLIDOPATERNO',	'APELLIDOMATERNO',	'CARGAS',	'LUGARNACI',	'FECNACIMIENTO',	'NACIONALIDAD',	'NIVELINSTRUC',	'DIRECDOMICILIO',	'REFERENCIADOMICILIO',	'LOCALIDADDOMICILIO',	'CIUDADDOMICILIO',	'COMISIONES',	'CUPOSOLICITADO',	'PROFESION',	'CONYUGUE',	'TIPODOCCONYUGUE',	'IDENTIFICACIONCONYU',	'TLFDOMIC1',	'TLFDOMIC2',	'CELULAR1',	'CELULAR2',	'SEXO',	'ESTADOCIVIL',	'EMAIL',	'EMAIL2',	'TIPOVIVIENDA',	'VALORRENTA',	'TIEMRESIDE',	'TRABAJO',	'DIRECTRABAJO',	'REFERENCIATRABAJO',	'LOCALIDADTRABAJO',	'CARGO',	'SUELDO',	'TIEMTRABAJO',	'CIUDADTRABAJO',	'TLFTRABA1',	'TLFTRABA2',	'EXTTRABA1',	'EXTTRABA2',	'OTROSINGRESOS',	'ORIGENOTROS',	'VALOROTROS',	'TRABAANTERIOR',	'CARGOANTERIOR',	'TLFTRABANTE',	'SUELDOANTERIOR',	'TRABACONYUGUE',	'DIRETRABACONYUGUE',	'CARGOCONYUGUE',	'TLFCONYUGUE',	'SUELDOCONYUGUE',	'REFECOMER1',	'REFECOMER2',	'TLFREFECOMER1',	'TLFREFECOMER2',	'PARIENTEUNO',	'PARENTESCOUNO',	'DIRECPARIUNO',	'TLFPARIUNO',	'PARIENTEDOS',	'PARENTESCODOS',	'DIRECPARIDOS',	'TLFPARIDOS',	'NOMBREPLASTICO',	'TIENDAENTREGA',	'CASILLA',	'CIUDADCASILLA',	'LOCALIDADCASILLA',	'ESTCTADOMICILIO',	'ESTCTATRABAJO',	'ESTCTACASILLA',	'MSGCOBRANZA',	'MSGSALDOS',	'MSGPROPAG',];

}
